[project]
name = "django-crm"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "django-daisy>=1.0.8",
    "django>=5.1.4",
    "psycopg2-binary>=2.9.10",
]
